version: "3.7"
services:
  web:
    #platform: Platform, x86_64
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/smartlyrics
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  db:
    image: postgres
    env_file:
      - .env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  postgres_data: